---

# this file is for the labeler workflow job
# Documentation https://github.com/marketplace/actions/labeler

"type: bug":
  - head-branch: ['^bug', '^fix', 'bug', 'fix']

"type: enhancement":
  - head-branch: ['^feature', '^feat', 'feature']

"type: documentation":
  - changed-files:
      - any-glob-to-any-file: ['assets/**/*', '.github/*', './*.md', '.cursor/*']

"type: maintenance":
  - changed-files:
      - any-glob-to-any-file: ['tests/**/*', '.github/workflows/*']

...
